### PR TITLE
Remove API Gateway extension from kyma-dashboard

### PR DESCRIPTION
**Pull request by barchw**
**Description**

Changes proposed in this pull request:

- Remove modularised content from API-Gateway
- Content was moved to [APIGateway repo](https://github.com/kyma-project/api-gateway/tree/main/config/ui-extensions/apirules)

**Related issue(s)**

### CODE REVIEW

**Comment by barchw** [comment]
/hold
API Gateway module 2.0.0 wasn't released with UI extension for API Rule. As so, we cannot delete the extension right now

**Review by mrCherry97 — CHANGES_REQUESTED** [review]
`functions-view.js` - also should be removed

**Review by mrCherry97 — APPROVED** [review]

**Review by mrCherry97 — APPROVED** [review]

**Pull request merged**
