### PR TITLE
Deprecate nodejs14, introduce nodejs18 runtime

### PR DESCRIPTION
**Pull request by kwiatekus**
**Description**

Changes proposed in this pull request:

- deprecate nodejs14 runtime
- introduce nodejs18

**Related issue(s)**
https://github.com/kyma-project/kyma/issues/16765
https://github.com/kyma-project/kyma/issues/16711
depends on https://github.com/kyma-project/kyma/pull/16918 🟢

### CODE REVIEW

**Comment by kwiatekus** [comment]
Would merge of this PR auto-progress the change into dashboard on prod?
I guess we'd need to wait until nodejs18 is available on SKRs (when 2.12 will be rolled-out to prod landscape)

**Comment by mrCherry97** [comment]
@kwiatekus ping us, when nodejs18 will be available on all SKRs, and then we will merge this. After merging, we will push dev/stage/prod to make it live.

**Review by mrCherry97 — APPROVED** [review]

**Pull request merged**
